# Laboratoire 2 : Arbre de désision, Bayes naïf et KNN
#### Département du génie logiciel et des technologies de l’information

| Étudiants             | Hugo LEMARCHANT - LEMH03039705 *                                    |
|-----------------------|---------------------------------------------------------|
| Cours                 | GTI770 - Systèmes intelligents et apprentissage machine |
| Session               | Automne 2018                                            |
| Groupe                | C                                                       |
| Numéro du laboratoire | 02                                                      |
| Professeur            | Prof. Hervé Lombaert                                    |
| Chargé de laboratoire | Pierre-Luc Delisle                                      |
| Date                  | 11/10/2018                                              |

DOCUMENTATION : 
Le prof a dit d'utiliser ça : http://scikit-learn.org/stable/auto_examples/svm/plot_rbf_parameters.html

In [83]:
# -*- coding:utf-8 -*-
import numpy as np
import cv2
import matplotlib.pyplot as plt
import sys
import os, random
import math
from sklearn import tree
from sklearn.model_selection import train_test_split, cross_val_score
import scipy.ndimage as nd
import csv
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import preprocessing

In [4]:
# Hugo
pathHugo = "E:\\DocsPerso\\DocsBoulot\\ETS-MTL\\GTI770-02-SystIntel&MachineLearning\\data\\data\\images\\"
# JS
pathJS= '/Users/jslecointre/Documents/DataScience/courses/MACHINE_LEARNING/TP/data/images/'
pathElodie = '/Users/raen/Documents/UTC/ETS/GTI770/GTI770-Data/images/'
exts = ".jpg"
nb_img = "2"
path = pathElodie

## Galaxy Zoo

In [ ]:
df = pd.read_csv('galaxy_feature_vectors.csv', delimiter = ',', header=None)
X_galaxy = df
df = pd.read_csv('galaxy_label_data_set.csv', delimiter = ',', header=None)
Y_galaxy = df

Xg_train, Xg_test, Yg_train, Yg_test = train_test_split(X_galaxy, Y_galaxy, test_size=0.20, random_state=42, stratify=Y_galaxy)

## Spam

In [46]:
df = pd.read_csv('spam.csv', delimiter = ',', header=None)
X_mail = df.loc[:, 0:56]
Y_mail = df.loc[:, 57]

Xm_train, Xm_test, Ym_train, Ym_test = train_test_split(X_mail, Y_mail, test_size=0.20, random_state=42, stratify=Y_mail)

### Arbres de décision - Cross-validation
#### Max-depth : none

In [48]:
clf_tree = tree.DecisionTreeClassifier()
scores = cross_val_score(clf_tree, X_mail, Y_mail, cv=5)
print(scores)

[0.91123188 0.90398551 0.90036232 0.9057971  0.90036232]


#### Max-depth : 3

In [56]:
clf_tree = tree.DecisionTreeClassifier(max_depth=3)
scores = cross_val_score(clf_tree, X_mail, Y_mail, cv=5)
print(scores)

[0.91304348 0.90036232 0.87862319 0.90036232 0.88405797]


#### Max-depth : 5

In [57]:
clf_tree = tree.DecisionTreeClassifier(max_depth=5)
scores = cross_val_score(clf_tree, X_mail, Y_mail, cv=5)
print(scores)

[0.92572464 0.91847826 0.88949275 0.90942029 0.88586957]


#### Max-depth : 10

In [58]:
clf_tree = tree.DecisionTreeClassifier(max_depth=10)
scores = cross_val_score(clf_tree, X_mail, Y_mail, cv=5)
print(scores)

[0.91847826 0.92753623 0.90036232 0.9057971  0.90942029]


### KNN - Cross-validation
#### K = 3, Poids = 'uniform' & Poids = 'distance'

In [64]:
clf_knn = KNeighborsClassifier(n_neighbors=3, weights='uniform')
scores = cross_val_score(clf_knn, X_mail, Y_mail, cv=5)
print(scores)

clf_knn = KNeighborsClassifier(n_neighbors=3, weights='distance')
scores = cross_val_score(clf_knn, X_mail, Y_mail, cv=5)
print(scores)

[0.78985507 0.77536232 0.79166667 0.7826087  0.77173913]
[0.80797101 0.78985507 0.78804348 0.80072464 0.78623188]


#### K = 5, Poids = 'uniform' & Poids = 'distance'

In [68]:
clf_knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
scores = cross_val_score(clf_knn, X_mail, Y_mail, cv=5)
print(scores)

clf_knn = KNeighborsClassifier(n_neighbors=5, weights='distance')
scores = cross_val_score(clf_knn, X_mail, Y_mail, cv=5)
print(scores)

[0.7826087  0.76992754 0.80434783 0.77173913 0.76268116]
[0.79891304 0.79166667 0.8134058  0.79347826 0.80253623]


#### K = 10, Poids = 'uniform' & Poids = 'distance'

In [71]:
clf_knn = KNeighborsClassifier(n_neighbors=10, weights='uniform')
scores = cross_val_score(clf_knn, X_mail, Y_mail, cv=5)
print(scores)

clf_knn = KNeighborsClassifier(n_neighbors=10, weights='distance')
scores = cross_val_score(clf_knn, X_mail, Y_mail, cv=5)
print(scores)

[0.76449275 0.74818841 0.77173913 0.78804348 0.75905797]
[0.80615942 0.7826087  0.80072464 0.80978261 0.79347826]


### Bayes Naive - Cross-validation

In [84]:
min_max_scaler = preprocessing.MinMaxScaler()
Xm_scaled = min_max_scaler.fit_transform(X_mail)
clf_bn = MultinomialNB()
scores = cross_val_score(clf_bn, Xm_scaled, Y_mail, cv=5)
print(scores)

[0.90036232 0.92028986 0.90217391 0.86594203 0.88949275]


## Question 1
### Méthode de création des ensembles de données

## Question 1
### Détails des ensembles produits

## Question 2
### Approche de validation proposée et justification

## Question 3
### Matrice des expérimentations

## Question 3
### Étude des hyperparamètres et des modèles

## Question 4
### Impact de la taille des ensembles de données sur la performance de classification

## Question 5
### Impact du bruit dans les ensembles de données sur la performance de classification

## Question 6
### Discussion sur la nature des données

## Question 7
### Recommandations

## Question 8
### Améliorations possibles